title: Mikayla's homepage
description: Mikayla's Home on GitHub Pages
github_username: Blakeym3155
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one